#!/bin/sh

cd /home/hetanjin/Mesmer/test/mesmerInput_1QOOH_woHR_50200
echo begin >> log.text
date >> log.text
echo ' ' >> log.text
for entry in `ls *.xml`
do
	echo $entry >> log.text
	tmp_var=out_$entry
	echo $tmp_var >> log.text
	/home/hetanjin/apps/Mesmer3.0/bin/mesmer ${entry} -o ${tmp_var} -N &

done

jobs -l >> log.text
wait
echo ' ' >> log.text
date >> log.text
echo allJobsFinished >> log.text


