var RegKeys =
'AH|AL|AX|BH|BL|BP|BX|CH|CL|CR0|CR2|CR3|CS|CX|DH|DI|DL|DR0|DR1|DR2|DR3|DR6|DR7|'+
'DS|DX|EAX|EBP|EBX|ECX|EDI|EDX|ES|ESI|ESP|FS|GS|MM0|MM1|MM2|MM3|MM4|MM5|MM6|MM7|'+
'SI|SP|SS|ST|TR3|TR4|TR5|TR6|TR7|XMM0|XMM1|XMM2|XMM3|XMM4|XMM5|XMM6|XMM7';

var CmdKeys1 =
'AAA|AAD|AAM|AAS|ADC|ADD|AND|ARPL|BOUND|BSF|BSR|BSWAP|BT|BTC|BTR|BTS|CALL|CBW|CDQ|CLC|CLD|CLI|'+
'CLTS|CMC|CMOVA|CMOVAE|CMOVB|CMOVBE|CMOVC|CMOVE|CMOVG|CMOVGE|CMOVL|CMOVLE|CMOVNA|CMOVNAE|CMOVNB|'+
'CMOVNBE|CMOVNC|CMOVNE|CMOVNG|CMOVNGE|CMOVNL|CMOVNLE|CMOVNO|CMOVNP|CMOVNS|CMOVNZ|CMOVO|CMOVP|'+
'CMOVPE|CMOVPO|CMOVS|CMOVZ|CMP|CMPS|CMPSB|CMPSD|CMPSW|CMPXCHG|CMPXCHG8B|CPUID|CWD|CWDE|DAA|DAS|'+
'DEC|DIV|ENTER|HLT|IDIV|IMUL|IN|INC|INS|INSB|INSD|INSW|INT|INTO|INVD|INVLPG|IRET|IRETD|IRETDF|'+
'IRETF|JA|JAE|JB|JBE|JC|JCXZ|JE|JECXZ|JG|JGE|JL|JLE|JMP|JNA|JNAE|JNB|JNBE|JNC|JNE|JNG|JNGE|JNL|'+
'JNLE|JNO|JNP|JNS|JNZ|JO|JP|JPE|JPO|JS|JZ|LAHF|LAR|LDS|LEA|LEAVE|LES|LFS|LGDT|LGS|LIDT|LLDT|'+
'LMSW|LOCK|LODS|LODSB|LODSD|LODSW|LOOP|LOOPD|LOOPE|LOOPED|LOOPEW|LOOPNE|LOOPNED|LOOPNEW|LOOPNZ|'+
'LOOPNZD|LOOPNZW|LOOPW|LOOPZ|LOOPZD|LOOPZW|LSL|LSS|LTR|MOV|MOVS|MOVSB|MOVSD|MOVSW|MOVSX|MOVZX|MUL|'+
'NEG|NOP|NOT|OR|OUT|OUTS|OUTSB|OUTSD|OUTSW|POP|POPA|POPAD|POPF|POPFD|PUSH|PUSHA|PUSHAD|PUSHAW|PUSHD|'+
'PUSHF|PUSHFD|PUSHW|RCL|RCR|RDMSR|RDTSC|REP|REPE|REPNE|REPNZ|REPZ|RET|RETF|RETN|ROL|ROR|RSM|SAHF|'+
'SAL|SAR|SBB|SCAS|SCASB|SCASD|SCASW|SETA|SETAE|SETB|SETBE|SETC|SETE|SETG|SETGE|SETL|SETLE|SETNA|'+
'SETNAE|SETNB|SETNBE|SETNC|SETNE|SETNG|SETNGE|SETNL|SETNLE|SETNO|SETNP|SETNS|SETNZ|SETO|SETP|SETPE|'+
'SETPO|SETS|SETZ|SGDT|SHL|SHLD|SHR|SHRD|SIDT|SLDT|SMSW|STC|STD|STI|STOS|STOSB|STOSD|STOSW|STR|SUB|'+
'TEST|VERR|VERW|WAIT|WBINVD|WRMSR|XADD|XCHG|XLAT|XLATB|XOR|F2XM1|FABS|FADD|FADDP|FBLD|FBSTP|FCHS|'+
'FCLEX|FCMOVA|FCMOVAE|FCMOVB|FCMOVBE|FCMOVE|FCMOVNA|FCMOVNAE|FCMOVNB|FCMOVNBE|FCMOVNE|FCMOVNU|'+
'FCMOVU|FCOM|FCOMI|FCOMIP|FCOMP|FCOMPP|FCOS|FDECSTP|FDISI|FDIV|FDIVP|FDIVR|FDIVRP|FENI|FFREE|FIADD|'+
'FICOM|FICOMP|FIDIV|FIDIVR|FILD|FIMUL|FINCSTP|FINIT|FIST|FISTP|FISUB|FISUBR|FLD|FLD1|FLDCW|FLDENV|'+
'FLDENVD|FLDENVW|FLDL2E|FLDL2T|FLDLG2|FLDLN2|FLDPI|FLDZ|FMUL|FMULP|FNCLEX|FNDISI|FNENI|FNINIT|FNOP|'+
'FNSAVE|FNSAVED|FNSAVEW|FNSTCW|FNSTENV|FNSTENVD|FNSTENVW|FNSTSW|FPATAN|FPREM|FPREM1|FPTAN|FRNDINT|'+
'FRSTOR|FRSTORD|FRSTORW|FSAVE|FSAVED|FSAVEW|FSCALE|FSETPM|FSIN|FSINCOS|FSQRT|FST|FSTCW|FSTENV|'+
'FSTENVD|FSTENVW|FSTP|FSTSW|FSUB|FSUBP|FSUBR|FSUBRP|FTST|FUCOM|FUCOMI|FUCOMIP|FUCOMP|FUCOMPP|'+
'FWAIT|FXAM|FXCH|FXTRACT|FYL2X|FYL2XP1|EMMS|FEMMS|FXRSTOR|FXSAVE|MOVD|MOVQ|PACKSSDW|PACKSSWB|'+
'PACKUSWB|PADDB|PADDD|PADDSB|PADDSW|PADDUSB|PADDUSW|PADDW|PAND|PANDN|PCMPEQB|PCMPEQD|PCMPEQW|'+
'PCMPGTB|PCMPGTD|PCMPGTW|PMADDWD|PMULHW|PMULLW|POR|PSLLD|PSLLQ|PSLLW|PSRAD|PSRAW|PSRLD|PSRLQ|'+
'SRLW|PSUBB|PSUBD|PSUBSB|PSUBSW|PSUBUSB|PSUBUSW|PSUBW|PUNPCKHBW|PUNPCKHDQ|PUNPCKHWD|PUNPCKLBW|'+
'PUNPCKLDQ|PUNPCKLWD|PXOR|ADDPS|ADDSS|ANDNPS|ANDPS|CMPPS|CMPSS|COMISS|CVTPI2PS|CVTPS2PI|CVTSI2SS|'+
'CVTSS2SI|CVTTPS2PI|CVTTSS2SI|DIVPS|DIVSS|LDMXCSR|MASKMOVQ|MAXPS|MAXSS|MINPS|MINSS|MOVAPS|MOVHLPS|'+
'MOVHPS|MOVLHPS|MOVLPS|MOVMSKPS|MOVNTPS|MOVNTQ|MOVSS|MOVUPS|MULPS|MULSS|ORPS|PAVGB|PAVGUSB|PAVGW|'+
'PEXTRW|PF2ID|PFACC|PFADD|PFCMPEQ|PFCMPGE|PFCMPGT|PFMAX|PFMIN|PFMUL|PFRCP|PFRCPIT1|PFRCPIT2|PFRSQRT|'+
'PFSUB|PFSUBR|PI2FD|PINSRW|PMAXSW|PMAXUB|PMINSW|PMINUB|PMOVMSKB|PMULHRW|PMULHUW|PREFETCH|PREFETCHNTA|'+
'PREFETCHT0|PREFETCHT1|PREFETCHT2|PSADBW|PSHUFW|RCPPS|RCPSS|RDPMC|RSQRTPS|RSQRTSS|SFENCE|SHUFPS|SQRTPS|'+
'SQRTSS|STMXCSR|SUBPS|SUBSS|SYSCALL|SYSENTER|SYSEXIT|SYSRET|UCOMISS|UNPCKHPS|UNPCKLPS|XORPS|ADDPD|ADDSD|'+
'ANDNPD|ANDPD|CLFLUSH|CMPPD|COMISD|CVTDQ2PD|CVTDQ2PS|CVTPD2DQ|CVTPD2PI|CVTPD2PS|CVTPDPS|CVTPI2PD|CVTPS2DQ|'+
'CVTPS2PD|CVTSD2SI|CVTSD2SS|CVTSI2SD|CVTSS2SD|CVTTPD2DQ|CVTTPD2PI|CVTTPS2DQ|CVTTPS2DQ|CVTTSD2SI|CVTTSI2SD|'+
'CVTTSI2SS|DIVPD|DIVSD|EXPORTS|FALSE|LFENCE|LIBRARY|MASKMOVDQU|MAXPD|MAXSD|MFENCE|MINPD|MINSD|MOVAPD|MOVDQ2Q|'+
'MOVDQA|MOVDQU|MOVHPD|MOVLPD|MOVMSKPD|MOVNIG|MOVNTDQ|MOVNTI|MOVNTPD|MOVQ2DQ|MOVQA|MOVSQ|MOVSXD|MOVUPD|MULPD|'+
'MULSD|NULL|ORPD|PACKUSDW|PADDQ|PF2IW|PFNACC|PFPNACC|PFRSQIT1|PI2FW|PMULUDQ|POPFQ|PSHUFD|PSHUFHW|PSHUFLW|'+
'PSLLDQ|PSRAQ|PSRLDQ|PSUBQ|PSWAPD|PUNPCKHQDQ|PUNPCKLQDQ|PUSHFQ|RDIVISR|SHUFPD|SQRTPD|SQRTSD|SUBPD|SUBSD|'+
'SWAPGS|TRUE|UCOMISD|UNPCKHPD|UNPCKLPD|XORPD';

var CmdKeys2 = 
'flat|HWND|LPARAM|UINT|WPARAM|ADDR|BASIC|BYTE|C|CARRY|DWORD|FAR|FAR16|FORTRAN|FWORD|NEAR|NEAR16|'+
'OVERFLOW|OWORD|PARITY|PASCAL|QWORD|REAL10|REAL4|REAL8|SBYTE|SDWORD|SIGN|STDCALL|SWORD|SYSCALL|'+
'TBYTE|VARARG|WORD|ZERO|OUT|186|286|286C|286P|287|386|386C|386P|387|486|486P|586|686|686p|8086|8087|'+
'ALPHA|CODE|CONST|CREF|DATA|DOSSEG|ERR|ERR1|ERR2|ERRB|ERRDEF|ERRDIF|ERRDIFI|ERRE|ERRIDN|ERRIDNI|'+
'ERRNB|ERRNDEF|ERRNZ|FARDATA|FARDATA|K3D|LALL|LFCOND|LIST|LISTALL|LISTIF|LISTMACRO|LISTMACROALL|'+
'MMX|MODEL|MSFLOAT|NO87|NOCREF|NOLIST|NOLISTIF|NOLISTMACRO|RADIX|SALL|SEQ|SFCOND|STACK|STARTUP|TFCOND|'+
'TYPE|XALL|XCREF|XLIST|XMM|ALIAS|ALIGN|ASSUME|CATSTR|COMM|DB|DD|DF|DOSSEG|DQ|DT|DUP|DW|ECHO|'+
'ELSE|ELSEIF|ELSEIF1|ELSEIF2|ELSEIFB|ELSEIFDEF|ELSEIFDIF|ELSEIFDIFI|ELSEIFE|ELSEIFIDN|ELSEIFIDNI|ELSEIFNB|'+
'ELSEIFNDEF|END|ENDIF|ENDM|ENDP|ENDS|endw|EQ|EQU|EVEN|EXITM|EXTERN|EXTERNDEF|EXTRN|FOR|FORC|GE|GOTO|GROUP|'+
'GT |HIGH|HIGHWORD|IF|IF1|IF2|IFB|IFDEF|IFDIF|IFDIFI|IFE|IFIDN|IFIDNI|IFNB|IFNDEF|INCLUDE|INCLUDELIB|INSTR|'+
'IRP|IRPC|LABEL|LE|LENGTH|LENGTHOF|LOCAL|LOW|LOWWORD|LROFFSET|LT |MACRO|MASK|MOD|NAME|NE|OFFSET|OPATTR|OPTION|'+
'ORG|PAGE|POPCONTEXT|PROC|PROTO|PTR|PUBLIC|PURGE|PUSHCONTEXT|RECORD|REPEAT|REPT|SEG|SEGMENT|SHORT|SIZE|SIZEOF|'+
'SIZESTR|STRUC|STRUCT|SUBSTR|SUBTITLE|SUBTTL|TEXTEQU|THIS|TITLE|TYPE|TYPEDEF|UNION|WHILE|WIDTH|BREAK|CONTINUE|'+
'ELSE|ELSEIF|ENDIF|ENDW|IF|REPEAT|UNTIL|UNTILCXZ|WHILE|INVOKE';
//LT GT后面有空格, 是为了避开 &lt; &gt;

var pres = document.getElementsByTagName("PRE");
for (var i=0; i< pres.length; i++) {
  if (pres[i].className == "asm") {
    str = pres[i].innerHTML;
    r1 = "(comment [&^][\\s\\S]*[&^]|;.*\\.asm)";
    r2 = "(^|\\s{1};.*)";
    r3 = '(".*?")';
    r4 = "('.*?'| \\S.*\\.inc| \\S.*\\.lib| \\S.*\\.asm)"; 
    r5 = "\\b([0-9]+[a-fA-F0-9]+[hH]{1})\\b";
    r6 = "\\b(?!\\d{1,2}8[678])(\\d+\\.?\\d*[fqodbrty]?|true|false|null)\\b"; 
    r7 = "\\b(" + RegKeys + ")\\b";
    r8 = "\\b(" + CmdKeys1 + ")\\b";
    r9 = "\\b(" + CmdKeys2 + ")\\b";
    rs = r1 + '|' + r2 + '|' + r3 + "|" + r4 + "|" + r5 + "|" + r6 + "|" + r7 + "|" + r8 + "|" + r9;

    rr = '<font color=#008000>$1$2</font>' +
         '<font color=#FF00FF>$3$4</font>' +
         '<font color=#0000FF>$5$6</font>' +
         '<font color=#0066CC><b>$7</b></font>' +
         '<font color=#FF0000><b>$8</b></font>' +
         '<font color=#800080><b>$9</b></font>';
         
    re = new RegExp(rs,"gi");
    str = str.replace(re, rr);
    str = str.replace(/\x20{4}/gm, '&nbsp;   ');
    pres[i].innerHTML = "<pre>" + str + "</pre>";
  }
}